In [1]:
import numpy as np
from numpy.linalg import inv

In [2]:
A=np.array([[0.49,0.31,0.2],[0.177,0.813,0.01],[0,0.01,0.99]])
print(A)

[[0.49  0.31  0.2  ]
 [0.177 0.813 0.01 ]
 [0.    0.01  0.99 ]]


In [3]:
import pandas as pd
df = pd.read_csv('CSVR.csv')

In [4]:
# Light spectra with respect to (Uniform,silvania,philips) _spectra and Unity object reflactances
li3=['C_lambda_U_R','C_lambda_S_R','C_lambda_P_R']
df[li3[0]]=df['uniform_spectra']
df[li3[1]]=df['silvania_spectra']
df[li3[2]]=df['philips_spectra']

In [5]:
# X(lambda),Y(lambda),Z(lambda) with respect to Uniform object reflactance and unity spectra
X_Lambda_U=np.dot(df['x'],df['C_lambda_U_R'])
Y_Lambda_U=np.dot(df['y'],df['C_lambda_U_R'])
Z_Lambda_U=np.dot(df['z'],df['C_lambda_U_R'])
XYZ_U=np.array([[X_Lambda_U],[Y_Lambda_U],[Z_Lambda_U]])
#print(XYZ_U)
XYZ_U.shape
RGB_U=np.dot(inv(A),XYZ_U)
print('R,G,B values with respect to Uniform object reflactance and unity spectra')
print(RGB_U*255)

R,G,B values with respect to Uniform object reflactance and unity spectra
[[255.00008371]
 [254.99993257]
 [255.00002515]]


In [6]:
# X(lambda),Y(lambda),Z(lambda) with respect to Uniform object reflactance and Silvania spectra
X_Lambda_S=np.dot(df['x'],df['C_lambda_S_R'])
Y_Lambda_S=np.dot(df['y'],df['C_lambda_S_R'])
Z_Lambda_S=np.dot(df['z'],df['C_lambda_S_R'])
XYZ_S=np.array([[X_Lambda_S],[Y_Lambda_S],[Z_Lambda_S]])
#print(XYZ_S)
XYZ_S.shape
RGB_S=np.dot(inv(A),XYZ_S)
print('R,G,B Values with respect to Uniform object reflactance and Silvania spectra')
print(RGB_S*255)

R,G,B Values with respect to Uniform object reflactance and Silvania spectra
[[175.12179326]
 [ 99.97248522]
 [ 33.24289222]]


In [7]:
# X(lambda),Y(lambda),Z(lambda) with respect to Uniform object reflactance and Philips spectra
X_Lambda_P=np.dot(df['x'],df['C_lambda_P_R'])
Y_Lambda_P=np.dot(df['y'],df['C_lambda_P_R'])
Z_Lambda_P=np.dot(df['z'],df['C_lambda_P_R'])
XYZ_P=np.array([[X_Lambda_P],[Y_Lambda_P],[Z_Lambda_P]])
#print(XYZ_P)
XYZ_P.shape
RGB_P=np.dot(inv(A),XYZ_P)
print('R,G,B Values with respect to Uniform object reflactance and Philips spectra')
print(RGB_P*255)

R,G,B Values with respect to Uniform object reflactance and Philips spectra
[[113.6077597 ]
 [ 50.87541779]
 [ 15.39310008]]


ALL Results at Once Printing

In [8]:
print('                RESULTS        ')
print('1.')
print(' Tristimulus R,G,B values with respect to Uniform object reflactance and   unity spectra')
print(RGB_U*255)
print(' ')
print('2')
print('Tristimulus  R,G,B Values with respect to Uniform object reflactance and   Silvania spectra')
print(RGB_S*255)
print('')
print('3')
print('Tristimulus   R,G,B Values with respect to Uniform object reflactance and Philips spectra')
print(RGB_P*255)

                RESULTS        
1.
 Tristimulus R,G,B values with respect to Uniform object reflactance and   unity spectra
[[255.00008371]
 [254.99993257]
 [255.00002515]]
 
2
Tristimulus  R,G,B Values with respect to Uniform object reflactance and   Silvania spectra
[[175.12179326]
 [ 99.97248522]
 [ 33.24289222]]

3
Tristimulus   R,G,B Values with respect to Uniform object reflactance and Philips spectra
[[113.6077597 ]
 [ 50.87541779]
 [ 15.39310008]]
