Importing required Libraries

In [ ]:
import numpy as np
from numpy.linalg import inv

In [ ]:
A=np.array([[0.49,0.31,0.2],[0.177,0.813,0.01],[0,0.01,0.99]]) 
print(A)

[[0.49  0.31  0.2  ]
 [0.177 0.813 0.01 ]
 [0.    0.01  0.99 ]]


In [ ]:
import pandas as pd
df = pd.read_csv('CSVR.csv')

In [ ]:
# Object reflactances of x,y,z
li1=['x','y','z']
li2=['R_Lambda_X','R_Lambda_Y','R_Lambda_Z']
i=0
for ele in li1:
  df[li2[i]]=df[ele]/df[ele].max()
  i=i+1

In [ ]:
# Light spectra with respect to Uniform_spectra and object reflactances
li3=['C_lambda_U_RX','C_lambda_U_RY','C_lambda_U_RZ']
df[li3[0]]=df['uniform_spectra']*df[li2[0]]
df[li3[1]]=df['uniform_spectra']*df[li2[1]]
df[li3[2]]=df['uniform_spectra']*df[li2[2]]

In [ ]:
# X(lambda),Y(lambda),Z(lambda) with respect to Uniform _Spectra and object reflactance as x
X_Lambda_U=np.dot(df['x'],df['C_lambda_U_RX'])
Y_Lambda_U=np.dot(df['y'],df['C_lambda_U_RX'])
Z_Lambda_U=np.dot(df['z'],df['C_lambda_U_RX'])
XYZ_U=np.array([[X_Lambda_U],[Y_Lambda_U],[Z_Lambda_U]])
#print(XYZ_U)
XYZ_U.shape
RGB_U=np.dot(inv(A),XYZ_U)

In [ ]:
# X(lambda),Y(lambda),Z(lambda) with respect to Uniform _Spectra and object reflactance as y
X_Lambda_UY=np.dot(df['x'],df['C_lambda_U_RY'])
Y_Lambda_UY=np.dot(df['y'],df['C_lambda_U_RY'])
Z_Lambda_UY=np.dot(df['z'],df['C_lambda_U_RY'])
XYZ_UY=np.array([[X_Lambda_UY],[Y_Lambda_UY],[Z_Lambda_UY]])
#print(XYZ_UY)
XYZ_UY.shape
RGB_UY=np.dot(inv(A),XYZ_UY)

In [ ]:
# X(lambda),Y(lambda),Z(lambda) with respect to Uniform _Spectra and object reflactance as z
X_Lambda_UZ=np.dot(df['x'],df['C_lambda_U_RZ'])
Y_Lambda_UZ=np.dot(df['y'],df['C_lambda_U_RZ'])
Z_Lambda_UZ=np.dot(df['z'],df['C_lambda_U_RZ'])
XYZ_UZ=np.array([[X_Lambda_UZ],[Y_Lambda_UZ],[Z_Lambda_UZ]])
#print(XYZ_UY)
XYZ_UZ.shape
RGB_UZ=np.dot(inv(A),XYZ_UZ)

In [ ]:
print(RGB_U*255)
print(RGB_UY*255)
print(RGB_UZ*255)

[[241.26373195]
 [103.35605037]
 [ 57.08384717]]
[[145.14673463]
 [194.78331419]
 [ 18.52774375]]
[[-17.14308374]
 [ 15.4051954 ]
 [189.61853405]]


Printing All Results at once

In [ ]:
print('        RESULTS')
print('1.')
print('  Tristimulus  R,G,B values with respect to Uniform spectra and Object reflactance as x')
print(RGB_U*255)
print(' ')
print('2')
print('  Tristimulus  R,G,B Values with respect to Uniform spectra and Object reflactance as y')
print(RGB_UY*255)
print('')
print('3')
print('  Tristimulus R,G,B Values with respect to Uniform spectra and object reflactance as z')
print(RGB_UZ*255)

        RESULTS
1.
  Tristimulus  R,G,B values with respect to Uniform spectra and Object reflactance as x
[[241.26373195]
 [103.35605037]
 [ 57.08384717]]
 
2
  Tristimulus  R,G,B Values with respect to Uniform spectra and Object reflactance as y
[[145.14673463]
 [194.78331419]
 [ 18.52774375]]

3
  Tristimulus R,G,B Values with respect to Uniform spectra and object reflactance as z
[[-17.14308374]
 [ 15.4051954 ]
 [189.61853405]]
